[green_agent]
endpoint = "http://green-agent-society:9021"

[[participants]]
role = "purple-society-student"
endpoint = "http://purple-society-student:9022"
agentbeats_id = "019c10da-59bf-7390-b4c0-652915699fc8"

[[participants]]
role = "red-society-tutor"
endpoint = "http://red-society-tutor:9023"
agentbeats_id = "019c10d6-08b1-7a83-9fb8-b8e35c78ad9e"

[config]
problem_statement = "Sort a list of integers in nondecreasing order."
buggy_solution = "def sort_nums(nums):\n    return nums.sort()\n"
num_turns = 7

[[config.expected_behavior]]
input = [
    [
        3,
        1,
        2,
    ],
]
output = [
    1,
    2,
    3,
]

[[config.expected_behavior]]
input = [
    [
        5,
        5,
        1,
    ],
]
output = [
    1,
    5,
    5,
]

[[config.expected_behavior]]
input = [
    [
        -1,
        0,
        -1,
    ],
]
output = [
    -1,
    -1,
    0,
]
